aggregation: mean
track: black
methods: [vae]
submission: 20t_eps11_10_10_w10stab_imagequal
attack_config:
  num_transformations: 20
  eps_list: [1/255, 1/255]
  step_size_alpha: 1
  n_iters: [10, 10]
  decoding_models: ["waves", "openai/consistency-decoder"]
  image_quality_multiplier: -1
